#!/bin/bash
# Auto-generated by linkedin-clay-sync
# 1. Deduplicates the Clay LinkedIn Connections table
# 2. Scrapes LinkedIn and pushes only new connections to Clay

WEBHOOK="https://api.clay.com/v3/sources/webhook/pull-in-data-from-a-webhook-104165c6-8b71-4ade-b87e-96ab041afd2f"
CLI="$(dirname "$0")/../src/cli.ts"
LOG="/tmp/linkedin-clay-sync.log"

echo "$(date): Starting daily LinkedIn→Clay sync" >> "$LOG"

# Step 1: Dedup — remove any duplicate rows in Clay
echo "$(date): Running dedup..." >> "$LOG"
npx tsx "$CLI" dedup >> "$LOG" 2>&1

# Step 2: Scrape LinkedIn and push new connections
echo "$(date): Running scrape..." >> "$LOG"
npx tsx "$CLI" scrape --webhook "$WEBHOOK" >> "$LOG" 2>&1

echo "$(date): Done" >> "$LOG"
