#!/bin/bash
# Auto-generated by linkedin-clay-sync
# Finds the latest LinkedIn Connections.csv and syncs new connections to Clay

DOWNLOADS="$HOME/Downloads"
CSV=$(find "$DOWNLOADS" -name "Connections.csv" -not -path "*/\.*" 2>/dev/null | sort -t_ -k1,1 | tail -1)

if [ -z "$CSV" ]; then
  echo "$(date): No Connections.csv found in Downloads" >> /tmp/linkedin-clay-sync.log
  exit 0
fi

echo "$(date): Syncing from $CSV" >> /tmp/linkedin-clay-sync.log
node "$(dirname "$0")/../src/cli.ts" sync "$CSV" --webhook "https://api.clay.com/v3/sources/webhook/pull-in-data-from-a-webhook-104165c6-8b71-4ade-b87e-96ab041afd2f" >> /tmp/linkedin-clay-sync.log 2>&1
